create table if not exists shveyka.materials (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  category text not null default 'raw_material',
  unit text not null default 'шт',
  current_stock numeric not null default 0,
  min_stock numeric not null default 0,
  price_per_unit numeric,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_materials_name
  on shveyka.materials (name);

create index if not exists idx_materials_category
  on shveyka.materials (category, is_active);

drop trigger if exists trg_materials_updated_at on shveyka.materials;
create trigger trg_materials_updated_at
before update on shveyka.materials
for each row execute function shveyka.touch_updated_at();

