create table if not exists shveyka.production_order_change_log (
  id bigint generated by default as identity primary key,
  order_id bigint not null references shveyka.production_orders(id) on delete cascade,
  change_type text not null default 'field_change',
  field_name text,
  old_value jsonb,
  new_value jsonb,
  note text,
  payload jsonb not null default '{}'::jsonb,
  changed_by bigint,
  created_at timestamptz not null default now()
);

create index if not exists idx_production_order_change_log_order
  on shveyka.production_order_change_log (order_id, created_at desc);

create index if not exists idx_production_order_change_log_field
  on shveyka.production_order_change_log (order_id, field_name);

create or replace function shveyka.log_production_order_field_change(
  p_order_id bigint,
  p_change_type text default 'field_change',
  p_field_name text default null,
  p_old_value jsonb default null,
  p_new_value jsonb default null,
  p_note text default null,
  p_payload jsonb default '{}'::jsonb,
  p_changed_by bigint default null
)
returns bigint
language plpgsql
as $$
declare
  v_id bigint;
begin
  insert into shveyka.production_order_change_log (
    order_id,
    change_type,
    field_name,
    old_value,
    new_value,
    note,
    payload,
    changed_by
  )
  values (
    p_order_id,
    coalesce(nullif(p_change_type, ''), 'field_change'),
    p_field_name,
    p_old_value,
    p_new_value,
    p_note,
    coalesce(p_payload, '{}'::jsonb),
    p_changed_by
  )
  returning id into v_id;

  return v_id;
end;
$$;
