alter table if exists shveyka.product_models
  add column if not exists source_payload jsonb not null default '{}'::jsonb;

create or replace function shveyka.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists shveyka.catalog_attribute_definitions (
  id bigint generated by default as identity primary key,
  key text not null unique,
  label text not null,
  description text,
  value_type text not null default 'text'
    check (value_type in ('text', 'number', 'boolean', 'date', 'json', 'select', 'multi_select')),
  scope text not null default 'model'
    check (scope in ('model', 'order', 'batch', 'operation')),
  source text not null default 'manual'
    check (source in ('manual', 'keycrm', 'production', 'warehouse')),
  is_required boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_catalog_attribute_definitions_key
  on shveyka.catalog_attribute_definitions (key);

create index if not exists idx_catalog_attribute_definitions_scope_active
  on shveyka.catalog_attribute_definitions (scope, is_active, sort_order);

drop trigger if exists trg_catalog_attribute_definitions_updated_at on shveyka.catalog_attribute_definitions;
create trigger trg_catalog_attribute_definitions_updated_at
before update on shveyka.catalog_attribute_definitions
for each row execute function shveyka.touch_updated_at();

create table if not exists shveyka.catalog_attribute_values (
  id bigint generated by default as identity primary key,
  product_model_id bigint not null references shveyka.product_models(id) on delete cascade,
  attribute_definition_id bigint not null references shveyka.catalog_attribute_definitions(id) on delete cascade,
  value_text text,
  value_number numeric,
  value_boolean boolean,
  value_date date,
  value_json jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_attribute_values_one_value_check check (
    num_nonnulls(value_text, value_number, value_boolean, value_date, value_json) >= 1
  )
);

create unique index if not exists idx_catalog_attribute_values_unique
  on shveyka.catalog_attribute_values (product_model_id, attribute_definition_id);

create index if not exists idx_catalog_attribute_values_model
  on shveyka.catalog_attribute_values (product_model_id);

create index if not exists idx_catalog_attribute_values_definition
  on shveyka.catalog_attribute_values (attribute_definition_id);

drop trigger if exists trg_catalog_attribute_values_updated_at on shveyka.catalog_attribute_values;
create trigger trg_catalog_attribute_values_updated_at
before update on shveyka.catalog_attribute_values
for each row execute function shveyka.touch_updated_at();
