-- Cutting task handoff for production batches
-- Shared tables live in the shveyka schema so CRM and worker-app use the same records.

create table if not exists shveyka.batch_tasks (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references shveyka.production_batches(id) on delete cascade,
  task_type text not null default 'cutting',
  assigned_role text not null default 'cutting',
  status text not null default 'pending',
  accepted_by_employee_id bigint references shveyka.employees(id),
  accepted_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  launched_by_user_id bigint references shveyka.users(id),
  launched_at timestamptz not null default now(),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_batch_tasks_batch_id
  on shveyka.batch_tasks (batch_id);

create index if not exists idx_batch_tasks_role_status
  on shveyka.batch_tasks (assigned_role, status);

create unique index if not exists idx_batch_tasks_one_active_per_batch
  on shveyka.batch_tasks (batch_id)
  where status not in ('cancelled', 'completed');

alter table shveyka.cutting_nastils
  add column if not exists task_id bigint references shveyka.batch_tasks(id) on delete set null,
  add column if not exists nastil_number text,
  add column if not exists reel_width_cm integer,
  add column if not exists reel_length_m numeric(8,2),
  add column if not exists fabric_color text,
  add column if not exists weight_kg numeric(8,1),
  add column if not exists quantity_per_nastil integer,
  add column if not exists remainder_kg numeric(8,1);

create index if not exists idx_cutting_nastils_task_id
  on shveyka.cutting_nastils (task_id);
