-- Миграция: Введение уровня Базовых Моделей (Конструктивов)
-- Дата: 2026-04-18

-- 1. Таблица базовых моделей (Конструктивов)
create table if not exists shveyka.base_models (
    id bigint generated by default as identity primary key,
    category_id bigint references shveyka.product_categories(id) on delete set null,
    name text not null, -- Например: 'Поло чоловіче "Гліб"'
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- 2. Добавляем связь в таблицу исполнений
alter table shveyka.product_models 
    add column if not exists base_model_id bigint references shveyka.base_models(id) on delete set null;

-- Индекс для быстрого поиска
create index if not exists idx_product_models_base_id on shveyka.product_models(base_model_id);

-- Комментарии
comment on table shveyka.base_models is 'Производственные конструктивы (лекала), объединяющие разные дизайны из KeyCRM';
