-- Миграция: Расширенный каталог продукции (Модели, Варианты, Категории)
-- Дата: 2026-04-18

-- 1. Таблица категорий (синхронизация с KeyCRM)
create table if not exists shveyka.product_categories (
    id bigint primary key, -- Используем ID из KeyCRM как первичный ключ
    parent_id bigint references shveyka.product_categories(id),
    name text not null,
    description text,
    is_active boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- 2. Расширение таблицы моделей
alter table shveyka.product_models 
    add column if not exists category_id bigint references shveyka.product_categories(id),
    add column if not exists gender text check (gender in ('male', 'female', 'unisex', 'boy', 'girl')),
    add column if not exists technical_specs jsonb not null default '{}'::jsonb,
    add column if not exists main_image_url text,
    add column if not exists gallery_urls text[] not null default '{}'::text[];

-- 3. Таблица вариантов изделий (Размеры / Артикулы / Offers)
create table if not exists shveyka.product_variants (
    id bigint primary key, -- KeyCRM Offer ID
    product_model_id bigint not null references shveyka.product_models(id) on delete cascade,
    sku text not null, -- Уникальный артикул конкретного размера
    barcode text,
    size text,
    color text,
    price numeric(12,2),
    purchased_price numeric(12,2),
    weight_grams numeric,
    is_active boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Индексы для быстрого поиска
create index if not exists idx_product_variants_model_id on shveyka.product_variants(product_model_id);
create unique index if not exists idx_product_variants_sku on shveyka.product_variants(sku);
create index if not exists idx_product_categories_parent on shveyka.product_categories(parent_id);

-- 4. Лог синхронизации каталога
create table if not exists shveyka.catalog_sync_log (
    id bigint generated by default as identity primary key,
    entity_type text not null, -- 'category', 'product', 'variant'
    external_id bigint not null,
    action text not null, -- 'create', 'update', 'delete'
    status text not null, -- 'success', 'error'
    payload jsonb,
    error_details text,
    created_at timestamptz not null default now()
);

-- Триггеры для updated_at
drop trigger if exists trg_product_categories_updated_at on shveyka.product_categories;
create trigger trg_product_categories_updated_at
    before update on shveyka.product_categories
    for each row execute function shveyka.touch_updated_at();

drop trigger if exists trg_product_variants_updated_at on shveyka.product_variants;
create trigger trg_product_variants_updated_at
    before update on shveyka.product_variants
    for each row execute function shveyka.touch_updated_at();

-- Комментарии к таблицам
comment on table shveyka.product_categories is 'Дерево категорий товаров, синхронизированное с KeyCRM';
comment on table shveyka.product_models is 'Карточки изделий (модели пошива)';
comment on table shveyka.product_variants is 'Конкретные размеры и артикулы (Offers) моделей';
