create table if not exists shveyka.route_cards (
  id bigint generated by default as identity primary key,
  product_model_id bigint not null references shveyka.product_models(id) on delete cascade,
  version integer not null default 1,
  is_active boolean not null default true,
  description text,
  weight_grams numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_route_cards_model_version
  on shveyka.route_cards (product_model_id, version);

create index if not exists idx_route_cards_model_active
  on shveyka.route_cards (product_model_id, is_active, version desc);

drop trigger if exists trg_route_cards_updated_at on shveyka.route_cards;
create trigger trg_route_cards_updated_at
before update on shveyka.route_cards
for each row execute function shveyka.touch_updated_at();

create table if not exists shveyka.operations (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  operation_type text not null default 'other',
  base_rate numeric not null default 0,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_operations_updated_at on shveyka.operations;
create trigger trg_operations_updated_at
before update on shveyka.operations
for each row execute function shveyka.touch_updated_at();

create table if not exists shveyka.route_card_operations (
  id bigint generated by default as identity primary key,
  route_card_id bigint not null references shveyka.route_cards(id) on delete cascade,
  operation_id bigint not null references shveyka.operations(id) on delete restrict,
  sequence_number integer not null,
  sequence_order integer not null,
  custom_rate numeric,
  is_mandatory boolean not null default true,
  is_required boolean not null default true,
  is_control_point boolean not null default false,
  batch_status_on_confirm text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_route_card_operations_unique
  on shveyka.route_card_operations (route_card_id, operation_id);

create index if not exists idx_route_card_operations_sequence
  on shveyka.route_card_operations (route_card_id, sequence_number);

drop trigger if exists trg_route_card_operations_updated_at on shveyka.route_card_operations;
create trigger trg_route_card_operations_updated_at
before update on shveyka.route_card_operations
for each row execute function shveyka.touch_updated_at();

create table if not exists shveyka.material_norms (
  id bigint generated by default as identity primary key,
  product_model_id bigint not null references shveyka.product_models(id) on delete cascade,
  material_id bigint not null references shveyka.materials(id) on delete restrict,
  quantity_per_unit numeric not null default 0,
  item_type text,
  unit_of_measure text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_material_norms_unique
  on shveyka.material_norms (product_model_id, material_id);

create index if not exists idx_material_norms_model
  on shveyka.material_norms (product_model_id, is_active);

drop trigger if exists trg_material_norms_updated_at on shveyka.material_norms;
create trigger trg_material_norms_updated_at
before update on shveyka.material_norms
for each row execute function shveyka.touch_updated_at();

create table if not exists shveyka.production_order_events (
  id bigint generated by default as identity primary key,
  order_id bigint not null references shveyka.production_orders(id) on delete cascade,
  action text not null,
  from_status text,
  to_status text,
  stage_label text,
  note text,
  payload jsonb not null default '{}'::jsonb,
  created_by bigint,
  created_at timestamptz not null default now()
);

create index if not exists idx_production_order_events_order
  on shveyka.production_order_events (order_id, created_at desc);

create table if not exists shveyka.material_requirements (
  id bigint generated by default as identity primary key,
  order_id bigint not null references shveyka.production_orders(id) on delete cascade,
  material_id bigint references shveyka.materials(id) on delete restrict,
  material_name text not null,
  required_quantity numeric not null default 0,
  available_quantity numeric not null default 0,
  shortage_quantity numeric not null default 0,
  unit text,
  item_type text,
  unit_of_measure text,
  calculation_source text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_material_requirements_unique
  on shveyka.material_requirements (order_id, material_id);

create index if not exists idx_material_requirements_order
  on shveyka.material_requirements (order_id);

drop trigger if exists trg_material_requirements_updated_at on shveyka.material_requirements;
create trigger trg_material_requirements_updated_at
before update on shveyka.material_requirements
for each row execute function shveyka.touch_updated_at();

create or replace function shveyka.log_production_order_event(
  p_order_id bigint,
  p_action text,
  p_from_status text default null,
  p_to_status text default null,
  p_stage_label text default null,
  p_note text default null,
  p_payload jsonb default '{}'::jsonb,
  p_created_by bigint default null
)
returns bigint
language plpgsql
as $$
declare
  v_id bigint;
begin
  insert into shveyka.production_order_events (
    order_id,
    action,
    from_status,
    to_status,
    stage_label,
    note,
    payload,
    created_by
  )
  values (
    p_order_id,
    p_action,
    p_from_status,
    p_to_status,
    p_stage_label,
    p_note,
    coalesce(p_payload, '{}'::jsonb),
    p_created_by
  )
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function shveyka.calculate_material_requirements(p_order_id bigint)
returns void
language plpgsql
as $$
begin
  delete from shveyka.material_requirements where order_id = p_order_id;

  insert into shveyka.material_requirements (
    order_id,
    material_id,
    material_name,
    required_quantity,
    available_quantity,
    shortage_quantity,
    unit,
    item_type,
    unit_of_measure,
    calculation_source,
    notes
  )
  select
    p_order_id as order_id,
    m.id as material_id,
    m.name as material_name,
    sum(coalesce(ol.quantity, 0) * coalesce(mn.quantity_per_unit, 0))::numeric as required_quantity,
    coalesce(m.current_stock, 0)::numeric as available_quantity,
    greatest(
      sum(coalesce(ol.quantity, 0) * coalesce(mn.quantity_per_unit, 0))::numeric - coalesce(m.current_stock, 0)::numeric,
      0
    ) as shortage_quantity,
    coalesce(m.unit, mn.unit_of_measure, 'шт') as unit,
    mn.item_type,
    coalesce(mn.unit_of_measure, m.unit, 'шт') as unit_of_measure,
    'material_norms' as calculation_source,
    null::text as notes
  from shveyka.production_order_lines ol
  join shveyka.product_models pm on pm.id = ol.model_id
  join shveyka.material_norms mn
    on mn.product_model_id = pm.id
   and mn.is_active = true
  join shveyka.materials m
    on m.id = mn.material_id
  where ol.order_id = p_order_id
  group by m.id, m.name, m.current_stock, m.unit, mn.unit_of_measure, mn.item_type;

  insert into shveyka.material_requirements (
    order_id,
    material_id,
    material_name,
    required_quantity,
    available_quantity,
    shortage_quantity,
    unit,
    item_type,
    unit_of_measure,
    calculation_source,
    notes
  )
  select
    p_order_id as order_id,
    null::bigint as material_id,
    'Норми не задані: ' || pm.name as material_name,
    sum(coalesce(ol.quantity, 0))::numeric as required_quantity,
    0::numeric as available_quantity,
    sum(coalesce(ol.quantity, 0))::numeric as shortage_quantity,
    'шт' as unit,
    'missing_norms' as item_type,
    'шт' as unit_of_measure,
    'missing_norms' as calculation_source,
    'Для моделі немає матеріальних норм' as notes
  from shveyka.production_order_lines ol
  join shveyka.product_models pm on pm.id = ol.model_id
  left join shveyka.material_norms mn
    on mn.product_model_id = pm.id
   and mn.is_active = true
  where ol.order_id = p_order_id
    and mn.id is null
  group by pm.id, pm.name;
end;
$$;
